### ISSUE TITLE
CORS blocking requests from svelte app

### ISSUE THREAD

**Issue by annazhurba** [tpalinski/bondz.io#2]
What:
CORS blocked request 

How to replicate:
Use bondzio.eat() 🐱 

Error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bondzioshed.bieda.it/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

**Comment by tpalinski** [comment]
Most likely CORS header missing server-side, going to fix it now

**Comment by tpalinski** [comment]
New version has been deployed, all tests pass, @annazhurba does the issue persist?

**Comment by annazhurba** [comment]
It works now, thanks!
